#!/usr/bin/env python3
"""
Phase 4: 生克 (Shēng-Kè) Foundation Data

Establishes infrastructure for the five-phase (五行) analysis and answers:
  Q1: 体/用 as scale bridge — how hexagram→trigram decomposition interacts with KW opposition
  Q2: 生克 in Hamming/mask terms — the combinatorial structure of the traditional mapping
  Q6: Five-phase cycle as combinatorial object — how special is the traditional assignment?

Encoding: L1 = bit 0 (bottom), L6 = bit 5 (top).
Trigrams are 3-bit integers with same bit ordering.
"""

from collections import Counter
from itertools import combinations, permutations
from pathlib import Path

import numpy as np

# ─── Constants ────────────────────────────────────────────────────────────────

N = 6
NUM_HEX = 1 << N        # 64
MASK_ALL = (1 << N) - 1  # 0b111111
NUM_TRIG = 8
MASK3 = 0b111

# ─── Trigram names ────────────────────────────────────────────────────────────

TRIGRAM_NAMES = {  # keyed by value where bit0=bottom line, bit2=top line
    0b000: "Kun ☷", 0b001: "Zhen ☳", 0b010: "Kan ☵", 0b011: "Dui ☱",
    0b100: "Gen ☶", 0b101: "Li ☲",   0b110: "Xun ☴", 0b111: "Qian ☰",
}

# ─── Five-phase (五行) system ─────────────────────────────────────────────────

ELEMENTS = ["Wood", "Fire", "Earth", "Metal", "Water"]
ELEMENT_ZH = {"Wood": "木", "Fire": "火", "Earth": "土", "Metal": "金", "Water": "水"}

# Trigram → Element (traditional mapping)
TRIGRAM_ELEMENT = {  # keyed by value where bit0=bottom line, bit2=top line
    0b111: "Metal", 0b011: "Metal",   # Qian ☰, Dui ☱
    0b101: "Fire",                     # Li ☲
    0b001: "Wood",  0b110: "Wood",     # Zhen ☳, Xun ☴
    0b010: "Water",                    # Kan ☵
    0b100: "Earth", 0b000: "Earth",    # Gen ☶, Kun ☷
}

# 生 (generation) cycle: Wood→Fire→Earth→Metal→Water→Wood
SHENG_CYCLE = ["Wood", "Fire", "Earth", "Metal", "Water"]
SHENG_EDGES = [(SHENG_CYCLE[i], SHENG_CYCLE[(i + 1) % 5]) for i in range(5)]

# 克 (overcoming) cycle: Wood→Earth→Water→Fire→Metal→Wood
KE_CYCLE = ["Wood", "Earth", "Water", "Fire", "Metal"]
KE_EDGES = [(KE_CYCLE[i], KE_CYCLE[(i + 1) % 5]) for i in range(5)]

# Precompute: element generates/overcomes which element
SHENG_MAP = {src: tgt for src, tgt in SHENG_EDGES}  # src generates tgt
KE_MAP = {src: tgt for src, tgt in KE_EDGES}        # src overcomes tgt

# Inverse maps for "who generates me" / "who overcomes me"
SHENG_INV = {tgt: src for src, tgt in SHENG_EDGES}  # tgt is generated by src
KE_INV = {tgt: src for src, tgt in KE_EDGES}        # tgt is overcome by src

# ─── Bit operations ──────────────────────────────────────────────────────────

def popcount(x):
    return bin(x).count('1')

def reverse6(x):
    r = 0
    for i in range(N):
        if x & (1 << i):
            r |= 1 << (N - 1 - i)
    return r

def fmt6(x):
    return format(x, '06b')

def fmt3(x):
    return format(x, '03b')

def bit(x, i):
    return (x >> i) & 1

# ─── Trigram extraction ──────────────────────────────────────────────────────

def lower_trigram(x):
    return x & MASK3

def upper_trigram(x):
    return (x >> 3) & MASK3

# ─── KW pairing ─────────────────────────────────────────────────────────────

def kw_partner(x):
    rev = reverse6(x)
    return x ^ MASK_ALL if rev == x else rev

def is_palindrome6(x):
    return reverse6(x) == x

def generate_kw_pairs():
    paired = set()
    pairs = []
    for a in range(NUM_HEX):
        if a in paired:
            continue
        b = kw_partner(a)
        ptype = "palindromic" if is_palindrome6(a) else "reversal"
        if a > b:
            a, b = b, a
        pairs.append((a, b, ptype))
        paired.add(a)
        paired.add(b)
    return pairs

# ─── Hexagram KW signature ──────────────────────────────────────────────────

def hex_kw_signature(x):
    """Return the 6-bit XOR mask and (o,m,i) signature for a hexagram's KW pair."""
    b = kw_partner(x)
    xor = x ^ b
    # For reversal pairs, xor is palindromic with signature (o,m,i)
    o = bit(xor, 0)
    m = bit(xor, 1)
    i = bit(xor, 2)
    return xor, (o, m, i)

# ─── Five-phase relationship ─────────────────────────────────────────────────

def five_phase_relation(ti_elem, yong_elem):
    """
    Evaluate the five-phase relationship from 体's perspective.
    Returns one of: 比和, 生体, 克体, 体生用, 体克用
    """
    if ti_elem == yong_elem:
        return "比和"
    if SHENG_MAP[yong_elem] == ti_elem:
        return "生体"      # 用 generates 体 → auspicious
    if KE_MAP[yong_elem] == ti_elem:
        return "克体"      # 用 overcomes 体 → harmful
    if SHENG_MAP[ti_elem] == yong_elem:
        return "体生用"    # 体 generates 用 → draining
    if KE_MAP[ti_elem] == yong_elem:
        return "体克用"    # 体 overcomes 用 → favorable
    raise ValueError(f"No relation found: {ti_elem} vs {yong_elem}")

# ─── Hamming distance (n=3) ─────────────────────────────────────────────────

def hamming3(a, b):
    return popcount(a ^ b)

# ─── Q1: 体/用 as Scale Bridge ──────────────────────────────────────────────

def compute_tiyong_states():
    """
    For every hexagram × moving line, compute 体/用 assignment and all derived quantities.
    Returns list of 384 state dicts.
    """
    states = []
    for h in range(NUM_HEX):
        lo, up = lower_trigram(h), upper_trigram(h)
        kw_xor, kw_sig = hex_kw_signature(h)

        for line in range(1, 7):  # 1-indexed moving line
            if line <= 3:
                # Moving in lower → lower=用, upper=体
                ti, yong = up, lo
            else:
                # Moving in upper → upper=用, lower=体
                ti, yong = lo, up

            ti_elem = TRIGRAM_ELEMENT[ti]
            yong_elem = TRIGRAM_ELEMENT[yong]
            relation = five_phase_relation(ti_elem, yong_elem)
            xor3 = ti ^ yong
            hd = popcount(xor3)

            states.append({
                'hex': h, 'line': line,
                'ti': ti, 'yong': yong,
                'ti_elem': ti_elem, 'yong_elem': yong_elem,
                'relation': relation,
                'xor3': xor3, 'hamming': hd,
                'kw_xor': kw_xor, 'kw_sig': kw_sig,
            })
    return states


def analyze_tiyong(states):
    """Compute summary statistics for Q1."""
    results = {}

    # Distribution of n=3 Hamming distances
    results['hamming_dist'] = Counter(s['hamming'] for s in states)

    # Distribution of n=3 XOR masks
    results['xor_dist'] = Counter(s['xor3'] for s in states)

    # Baseline: all 64 ordered trigram pairs (or 28 unordered non-self pairs)
    baseline_hamming = Counter()
    for a in range(NUM_TRIG):
        for b in range(NUM_TRIG):
            baseline_hamming[hamming3(a, b)] += 1
    results['baseline_hamming'] = baseline_hamming

    # Cross-tabulation: KW signature × Hamming distance
    sig_x_hamming = {}
    for s in states:
        key = (s['kw_sig'], s['hamming'])
        sig_x_hamming[key] = sig_x_hamming.get(key, 0) + 1
    results['sig_x_hamming'] = sig_x_hamming

    # Cross-tabulation: KW signature × five-phase relation
    sig_x_phase = {}
    for s in states:
        key = (s['kw_sig'], s['relation'])
        sig_x_phase[key] = sig_x_phase.get(key, 0) + 1
    results['sig_x_phase'] = sig_x_phase

    # KW partner complementarity analysis
    pairs = generate_kw_pairs()
    partner_map = {}
    for a, b, _ in pairs:
        partner_map[a] = b
        partner_map[b] = a

    # Index states by (hex, line)
    state_idx = {(s['hex'], s['line']): s for s in states}

    # For each KW pair × line position, compare relations
    complementarity = []
    for a, b, ptype in pairs:
        for line in range(1, 7):
            sa = state_idx[(a, line)]
            sb = state_idx[(b, line)]
            complementarity.append({
                'a': a, 'b': b, 'ptype': ptype, 'line': line,
                'rel_a': sa['relation'], 'rel_b': sb['relation'],
                'ti_a': sa['ti'], 'yong_a': sa['yong'],
                'ti_b': sb['ti'], 'yong_b': sb['yong'],
            })

    # Distribution of (rel_a, rel_b) pairs
    results['complementarity_dist'] = Counter(
        (c['rel_a'], c['rel_b']) for c in complementarity
    )
    results['complementarity'] = complementarity

    return results


# ─── Q2: 生克 in Hamming/Mask Terms ─────────────────────────────────────────

def analyze_shengke_structure():
    """Full analysis of the five-phase mapping in Hamming/mask terms."""
    results = {}

    # Element → trigrams
    elem_trigrams = {}
    for t, e in TRIGRAM_ELEMENT.items():
        elem_trigrams.setdefault(e, []).append(t)
    for e in elem_trigrams:
        elem_trigrams[e].sort()
    results['elem_trigrams'] = elem_trigrams

    # 1. Intra-element structure
    intra = {}
    for e, trigs in elem_trigrams.items():
        if len(trigs) == 2:
            a, b = trigs
            intra[e] = {'a': a, 'b': b, 'xor': a ^ b, 'hamming': hamming3(a, b)}
    results['intra'] = intra

    # 2. 生-relationship structure
    sheng_pairs = []
    for src, tgt in SHENG_EDGES:
        for ts in elem_trigrams[src]:
            for tt in elem_trigrams[tgt]:
                sheng_pairs.append({
                    'src_elem': src, 'tgt_elem': tgt,
                    'src_trig': ts, 'tgt_trig': tt,
                    'xor': ts ^ tt, 'hamming': hamming3(ts, tt),
                })
    results['sheng_pairs'] = sheng_pairs
    results['sheng_hamming_dist'] = Counter(p['hamming'] for p in sheng_pairs)

    # 3. 克-relationship structure
    ke_pairs = []
    for src, tgt in KE_EDGES:
        for ts in elem_trigrams[src]:
            for tt in elem_trigrams[tgt]:
                ke_pairs.append({
                    'src_elem': src, 'tgt_elem': tgt,
                    'src_trig': ts, 'tgt_trig': tt,
                    'xor': ts ^ tt, 'hamming': hamming3(ts, tt),
                })
    results['ke_pairs'] = ke_pairs
    results['ke_hamming_dist'] = Counter(p['hamming'] for p in ke_pairs)

    # 4. Full 8×8 trigram interaction matrix
    matrix = {}
    for a in range(NUM_TRIG):
        for b in range(NUM_TRIG):
            ea, eb = TRIGRAM_ELEMENT[a], TRIGRAM_ELEMENT[b]
            rel = five_phase_relation(ea, eb)  # a=体, b=用
            matrix[(a, b)] = {
                'xor': a ^ b, 'hamming': hamming3(a, b), 'relation': rel,
            }
    results['matrix'] = matrix

    # 5. Hamming profiles by relationship type
    rel_hamming = {}
    for (a, b), info in matrix.items():
        if a == b:
            continue  # skip self-pairs for comparison
        rel_hamming.setdefault(info['relation'], []).append(info['hamming'])
    results['rel_hamming'] = {r: Counter(hds) for r, hds in rel_hamming.items()}

    return results


# ─── Q6: Five-Phase Cycle as Combinatorial Object ───────────────────────────

def enumerate_assignments():
    """
    Enumerate all surjections from 8 trigrams → 5 elements with partition (2,2,2,1,1).
    
    Strategy: choose which 3 elements get 2 trigrams (C(5,3)=10 ways),
    then assign trigrams to the 5 distinguishable element slots.
    
    Total = C(5,3) × C(8,2) × C(6,2) × C(4,2) × C(2,1) × C(1,1)
          = 10 × 28 × 15 × 6 × 2 × 1
          = 50400
    """
    trigrams = list(range(NUM_TRIG))
    assignments = []

    # Choose which 3 of 5 elements get pairs (size 2)
    for pair_elems in combinations(range(5), 3):
        single_elems = [i for i in range(5) if i not in pair_elems]

        # Assign 2 trigrams to each pair-element, then 1 each to singletons.
        # Elements are distinguishable, so no deduplication of the three pair-groups.
        for t0 in combinations(trigrams, 2):
            remaining1 = [t for t in trigrams if t not in t0]
            for t1 in combinations(remaining1, 2):
                remaining2 = [t for t in remaining1 if t not in t1]
                for t2 in combinations(remaining2, 2):
                    remaining3 = [t for t in remaining2 if t not in t2]
                    # remaining3 has exactly 2 trigrams → assign to single_elems
                    for perm in permutations(remaining3):
                        mapping = {}
                        for t in t0:
                            mapping[t] = pair_elems[0]
                        for t in t1:
                            mapping[t] = pair_elems[1]
                        for t in t2:
                            mapping[t] = pair_elems[2]
                        for i, t in enumerate(perm):
                            mapping[t] = single_elems[i]
                        assignments.append(mapping)

    return assignments


def score_assignment(mapping):
    """
    Compute Hamming coherence and opposition preservation scores for a trigram→element assignment.
    
    The 生 and 克 cycles are fixed on abstract elements (0-4).
    The mapping tells us which trigrams belong to which element.
    """
    # Element → trigrams for this mapping
    elem_trigs = {}
    for t, e in mapping.items():
        elem_trigs.setdefault(e, []).append(t)

    # Abstract element cycles (indices into ELEMENTS)
    # 生: 0→1→2→3→4→0 (Wood→Fire→Earth→Metal→Water)
    # 克: 0→2→4→1→3→0 (Wood→Earth→Water→Fire→Metal)
    sheng_edges_idx = [(i, (i + 1) % 5) for i in range(5)]
    ke_edges_idx = [(0, 2), (2, 4), (4, 1), (1, 3), (3, 0)]

    def edge_stats(edges):
        """Compute mean Hamming and complement fraction for a set of directed edges."""
        total_hamming = 0
        total_pairs = 0
        complement_count = 0  # pairs at max Hamming distance (d=3)
        for src_e, tgt_e in edges:
            src_trigs = elem_trigs.get(src_e, [])
            tgt_trigs = elem_trigs.get(tgt_e, [])
            for ts in src_trigs:
                for tt in tgt_trigs:
                    h = hamming3(ts, tt)
                    total_hamming += h
                    total_pairs += 1
                    if h == 3:
                        complement_count += 1
        mean_h = total_hamming / total_pairs if total_pairs > 0 else 0
        comp_frac = complement_count / total_pairs if total_pairs > 0 else 0
        return mean_h, comp_frac, total_pairs

    # Intra-element coherence: mean Hamming within elements (lower = more coherent)
    intra_hamming = 0
    intra_count = 0
    for e_idx in range(5):
        trigs = elem_trigs.get(e_idx, [])
        for i in range(len(trigs)):
            for j in range(i + 1, len(trigs)):
                intra_hamming += hamming3(trigs[i], trigs[j])
                intra_count += 1
    intra_mean = intra_hamming / intra_count if intra_count > 0 else 0

    sheng_h, sheng_comp, sheng_n = edge_stats(sheng_edges_idx)
    ke_h, ke_comp, ke_n = edge_stats(ke_edges_idx)

    return {
        'sheng_hamming': sheng_h,
        'sheng_comp_frac': sheng_comp,
        'sheng_n': sheng_n,
        'ke_hamming': ke_h,
        'ke_comp_frac': ke_comp,
        'ke_n': ke_n,
        'intra_hamming': intra_mean,
    }


def find_traditional_index(assignments):
    """Find the index of the traditional mapping in the enumerated assignments."""
    # Traditional: element index mapping
    # 0=Wood, 1=Fire, 2=Earth, 3=Metal, 4=Water
    trad = {}
    for t, e_name in TRIGRAM_ELEMENT.items():
        trad[t] = ELEMENTS.index(e_name)

    for i, m in enumerate(assignments):
        if m == trad:
            return i
    return -1


# ─── Markdown formatting ────────────────────────────────────────────────────

def format_markdown(tiyong_states, tiyong_results, shengke_results, q6_data):
    lines = []
    w = lines.append

    w("# Phase 4: 生克 (Shēng-Kè) Foundation Data\n")
    w("Five-phase (五行) analysis of the KW pairing and trigram→element mapping.")
    w("Encoding: L1=bit0 (bottom) … L6=bit5 (top). Trigrams as 3-bit integers.\n")

    # ── Setup ──
    w("## 0. Traditional Mapping\n")
    w("### Trigram → Element\n")
    w("| Trigram | Binary | Element | Element (ZH) |")
    w("|---------|--------|---------|-------------|")
    for t in range(NUM_TRIG):
        e = TRIGRAM_ELEMENT[t]
        w(f"| {TRIGRAM_NAMES[t]} | {fmt3(t)} | {e} | {ELEMENT_ZH[e]} |")
    w("")

    w("### Five-phase cycles\n")
    w(f"**生 (generation):** {' → '.join(SHENG_CYCLE)} → {SHENG_CYCLE[0]}")
    w(f"**克 (overcoming):** {' → '.join(KE_CYCLE)} → {KE_CYCLE[0]}\n")

    w("### Element → Trigrams\n")
    w("| Element | Trigrams | Count |")
    w("|---------|----------|-------|")
    for e in ELEMENTS:
        trigs = shengke_results['elem_trigrams'][e]
        trig_str = ', '.join(f"{TRIGRAM_NAMES[t]} ({fmt3(t)})" for t in trigs)
        w(f"| {e} ({ELEMENT_ZH[e]}) | {trig_str} | {len(trigs)} |")
    w("")

    # ══════════════════════════════════════════════════════════════════════
    # Q1: 体/用 as Scale Bridge
    # ══════════════════════════════════════════════════════════════════════
    w("## Q1: 体/用 as Scale Bridge\n")
    w("384 states = 64 hexagrams × 6 moving lines.")
    w("Moving in lower → lower=用, upper=体. Moving in upper → upper=用, lower=体.\n")

    # Hamming distance distribution
    w("### 1.1 Hamming Distance Distribution (体 vs 用)\n")
    hd = tiyong_results['hamming_dist']
    total = sum(hd.values())
    w("| Hamming d | Count | Fraction | Baseline (all 8×8) |")
    w("|-----------|-------|----------|-------------------|")
    bd = tiyong_results['baseline_hamming']
    bd_total = sum(bd.values())
    for d in range(4):
        frac = hd.get(d, 0) / total
        bfrac = bd.get(d, 0) / bd_total
        w(f"| {d} | {hd.get(d, 0)} | {frac:.4f} | {bfrac:.4f} |")
    w("")
    mean_hd = sum(d * hd.get(d, 0) for d in range(4)) / total
    mean_bd = sum(d * bd.get(d, 0) for d in range(4)) / bd_total
    w(f"**Mean Hamming (体/用):** {mean_hd:.4f}")
    w(f"**Mean Hamming (baseline all pairs):** {mean_bd:.4f}")
    w(f"**Bias:** {'toward low (similar)' if mean_hd < mean_bd else 'toward high (different)' if mean_hd > mean_bd else 'neutral'}\n")

    # XOR mask distribution
    w("### 1.2 XOR Mask Distribution (体 ⊕ 用)\n")
    xd = tiyong_results['xor_dist']
    w("| XOR mask | Count | Fraction | Hamming |")
    w("|----------|-------|----------|---------|")
    for mask in range(8):
        cnt = xd.get(mask, 0)
        w(f"| {fmt3(mask)} | {cnt} | {cnt/total:.4f} | {popcount(mask)} |")
    w("")

    # Cross-tab: signature × Hamming
    w("### 1.3 Cross-Tabulation: KW Signature × Hamming Distance\n")
    w("KW signature (o,m,i) for the hexagram's KW pair; Hamming = distance between 体 and 用 trigrams.\n")
    sigs = sorted(set(s['kw_sig'] for s in tiyong_states))
    w("| Signature | d=0 | d=1 | d=2 | d=3 | Total | Mean d |")
    w("|-----------|-----|-----|-----|-----|-------|--------|")
    sxh = tiyong_results['sig_x_hamming']
    for sig in sigs:
        counts = [sxh.get((sig, d), 0) for d in range(4)]
        t = sum(counts)
        mean = sum(d * counts[d] for d in range(4)) / t if t > 0 else 0
        w(f"| {sig} | {counts[0]} | {counts[1]} | {counts[2]} | {counts[3]} | {t} | {mean:.2f} |")
    w("")

    # Note: palindromic hexagrams have signature (1,1,1) since comp XOR = 111111
    # But kw_sig extracts bits 0,1,2 which for complement = all 1s → (1,1,1)
    # For reversal pairs, the signature is the mirror-pair signature

    # Cross-tab: signature × five-phase
    w("### 1.4 Cross-Tabulation: KW Signature × Five-Phase Relation\n")
    relations = ["比和", "生体", "克体", "体生用", "体克用"]
    sxp = tiyong_results['sig_x_phase']
    header = "| Signature | " + " | ".join(relations) + " |"
    w(header)
    w("|-----------|" + "|".join(["---"] * len(relations)) + "|")
    for sig in sigs:
        counts = [sxp.get((sig, r), 0) for r in relations]
        w(f"| {sig} | " + " | ".join(str(c) for c in counts) + " |")
    w("")

    # KW partner complementarity
    w("### 1.5 KW Partner 体/用 Complementarity\n")
    w("For each KW pair (a,b) at same moving line: what is rel(a) vs rel(b)?\n")
    cd = tiyong_results['complementarity_dist']
    w("| rel(a) | rel(b) | Count |")
    w("|--------|--------|-------|")
    for (ra, rb), cnt in sorted(cd.items(), key=lambda x: -x[1]):
        w(f"| {ra} | {rb} | {cnt} |")
    w("")

    # Diagonal analysis: how often do partners share same relation?
    same = sum(cnt for (ra, rb), cnt in cd.items() if ra == rb)
    total_comp = sum(cd.values())
    w(f"**Same relation:** {same}/{total_comp} = {same/total_comp:.4f}")
    w(f"**Different relation:** {total_comp-same}/{total_comp} = {(total_comp-same)/total_comp:.4f}\n")

    # Most common complementary patterns
    w("**Key patterns (top 10):**\n")
    w("| rel(a) | rel(b) | Count | Complementary? |")
    w("|--------|--------|-------|----------------|")
    for (ra, rb), cnt in sorted(cd.items(), key=lambda x: -x[1])[:10]:
        # "Complementary" = one is auspicious, other harmful
        is_comp = (ra in ("生体", "体克用") and rb in ("克体", "体生用")) or \
                  (rb in ("生体", "体克用") and ra in ("克体", "体生用"))
        w(f"| {ra} | {rb} | {cnt} | {'✓' if is_comp else '✗'} |")
    w("")

    # ══════════════════════════════════════════════════════════════════════
    # Q2: 生克 in Hamming/Mask Terms
    # ══════════════════════════════════════════════════════════════════════
    w("## Q2: 生克 in Hamming/Mask Terms\n")

    # 2.1 Intra-element
    w("### 2.1 Intra-Element Structure\n")
    w("Trigrams the tradition treats as 'same element' (比和).\n")
    w("| Element | Trig A | Trig B | XOR | Hamming |")
    w("|---------|--------|--------|-----|---------|")
    intra = shengke_results['intra']
    for e in ELEMENTS:
        if e in intra:
            d = intra[e]
            w(f"| {e} | {TRIGRAM_NAMES[d['a']]} ({fmt3(d['a'])}) | {TRIGRAM_NAMES[d['b']]} ({fmt3(d['b'])}) | {fmt3(d['xor'])} | {d['hamming']} |")
        else:
            trigs = shengke_results['elem_trigrams'][e]
            w(f"| {e} | {TRIGRAM_NAMES[trigs[0]]} ({fmt3(trigs[0])}) | (singleton) | — | — |")
    w("")

    # 2.2 生-relationship structure
    w("### 2.2 生 (Generation) Relationship Structure\n")
    w("All trigram pairs where element(src) generates element(tgt).\n")
    w("| Edge | Src trig | Tgt trig | XOR | Hamming |")
    w("|------|----------|----------|-----|---------|")
    for p in shengke_results['sheng_pairs']:
        w(f"| {p['src_elem']}→{p['tgt_elem']} "
          f"| {TRIGRAM_NAMES[p['src_trig']]} ({fmt3(p['src_trig'])}) "
          f"| {TRIGRAM_NAMES[p['tgt_trig']]} ({fmt3(p['tgt_trig'])}) "
          f"| {fmt3(p['xor'])} | {p['hamming']} |")
    w("")
    sh = shengke_results['sheng_hamming_dist']
    sh_total = sum(sh.values())
    sh_mean = sum(d * sh.get(d, 0) for d in range(4)) / sh_total
    w(f"**生 Hamming distribution:** {dict(sorted(sh.items()))}")
    w(f"**生 mean Hamming:** {sh_mean:.4f}\n")

    # 2.3 克-relationship structure
    w("### 2.3 克 (Overcoming) Relationship Structure\n")
    w("All trigram pairs where element(src) overcomes element(tgt).\n")
    w("| Edge | Src trig | Tgt trig | XOR | Hamming |")
    w("|------|----------|----------|-----|---------|")
    for p in shengke_results['ke_pairs']:
        w(f"| {p['src_elem']}→{p['tgt_elem']} "
          f"| {TRIGRAM_NAMES[p['src_trig']]} ({fmt3(p['src_trig'])}) "
          f"| {TRIGRAM_NAMES[p['tgt_trig']]} ({fmt3(p['tgt_trig'])}) "
          f"| {fmt3(p['xor'])} | {p['hamming']} |")
    w("")
    kh = shengke_results['ke_hamming_dist']
    kh_total = sum(kh.values())
    kh_mean = sum(d * kh.get(d, 0) for d in range(4)) / kh_total
    w(f"**克 Hamming distribution:** {dict(sorted(kh.items()))}")
    w(f"**克 mean Hamming:** {kh_mean:.4f}\n")

    # 2.4 Full 8×8 matrix
    w("### 2.4 Full 8×8 Trigram Interaction Matrix\n")
    w("体 (rows) × 用 (columns). Cell = Hamming distance / relation initial.\n")
    rel_initials = {"比和": "H", "生体": "A", "克体": "X", "体生用": "D", "体克用": "F"}
    header = "|  体\\用  | " + " | ".join(f"{fmt3(b)}" for b in range(NUM_TRIG)) + " |"
    w(header)
    w("|--------|" + "|".join(["----"] * NUM_TRIG) + "|")
    mat = shengke_results['matrix']
    for a in range(NUM_TRIG):
        cells = []
        for b in range(NUM_TRIG):
            info = mat[(a, b)]
            cells.append(f"d{info['hamming']}{rel_initials[info['relation']]}")
        w(f"| {fmt3(a)} | " + " | ".join(cells) + " |")
    w("")
    w("Legend: d=Hamming distance, H=比和(harmonious), A=生体(auspicious), X=克体(harmful), D=体生用(draining), F=体克用(favorable)\n")

    # 2.5 Hamming profiles by relationship
    w("### 2.5 Hamming Distance by Five-Phase Relationship\n")
    w("Excluding self-pairs (a=b). How does each relationship distribute over Hamming distances?\n")
    rh = shengke_results['rel_hamming']
    w("| Relation | d=0 | d=1 | d=2 | d=3 | Total | Mean d |")
    w("|----------|-----|-----|-----|-----|-------|--------|")
    for rel in relations:
        if rel in rh:
            hcounts = rh[rel]
            cts = [hcounts.get(d, 0) for d in range(4)]
            t = sum(cts)
            mean = sum(d * cts[d] for d in range(4)) / t if t > 0 else 0
            w(f"| {rel} | {cts[0]} | {cts[1]} | {cts[2]} | {cts[3]} | {t} | {mean:.4f} |")
    w("")

    # Comparison
    w("**Key finding:** Do 生 and 克 differ systematically in Hamming profile?\n")
    w(f"- 生 (generation): mean d = {sh_mean:.4f}")
    w(f"- 克 (overcoming): mean d = {kh_mean:.4f}")
    if abs(sh_mean - kh_mean) < 0.1:
        w("- **Result:** No significant difference — both span similar Hamming distances.\n")
    else:
        w(f"- **Result:** Differ by {abs(sh_mean - kh_mean):.4f} — "
          f"{'生 is more distant' if sh_mean > kh_mean else '克 is more distant'}.\n")

    # ══════════════════════════════════════════════════════════════════════
    # Q6: Five-Phase Cycle as Combinatorial Object
    # ══════════════════════════════════════════════════════════════════════
    w("## Q6: Five-Phase Cycle as Combinatorial Object\n")

    n_assign = q6_data['n_assignments']
    trad_idx = q6_data['trad_idx']
    trad_scores = q6_data['trad_scores']
    all_sheng_h = q6_data['all_sheng_hamming']
    all_ke_h = q6_data['all_ke_hamming']
    all_sheng_comp = q6_data['all_sheng_comp']
    all_ke_comp = q6_data['all_ke_comp']
    all_intra_h = q6_data['all_intra_hamming']

    w(f"### Enumeration\n")
    w(f"Total valid surjections (8 trigrams → 5 elements, partition 2,2,2,1,1): **{n_assign}**\n")
    w(f"Traditional assignment found at index: {trad_idx}\n")

    w(f"### Traditional Assignment Scores\n")
    w(f"| Metric | 生 (generation) | 克 (overcoming) | Overall |")
    w(f"|--------|-----------------|-----------------|---------|")
    w(f"| Mean Hamming | {trad_scores['sheng_hamming']:.4f} | {trad_scores['ke_hamming']:.4f} | — |")
    w(f"| Complement fraction (d=3) | {trad_scores['sheng_comp_frac']:.4f} | {trad_scores['ke_comp_frac']:.4f} | — |")
    w(f"| Intra-element Hamming | — | — | {trad_scores['intra_hamming']:.4f} |")
    w(f"| Edge pair count | {trad_scores['sheng_n']} | {trad_scores['ke_n']} | — |")
    w("")

    # Ranking
    def percentile_rank(arr, val):
        arr = np.array(arr)
        return 100.0 * np.sum(arr <= val) / len(arr)

    sh_pct = percentile_rank(all_sheng_h, trad_scores['sheng_hamming'])
    kh_pct = percentile_rank(all_ke_h, trad_scores['ke_hamming'])
    sc_pct = percentile_rank(all_sheng_comp, trad_scores['sheng_comp_frac'])
    kc_pct = percentile_rank(all_ke_comp, trad_scores['ke_comp_frac'])
    ih_pct = percentile_rank(all_intra_h, trad_scores['intra_hamming'])

    def interp(pct):
        if pct < 5 or pct > 95: return 'extreme'
        if pct < 25 or pct > 75: return 'moderate'
        return 'average'

    w(f"### Ranking Among All {n_assign} Assignments\n")
    w(f"| Metric | Traditional value | Percentile | Interpretation |")
    w(f"|--------|-------------------|------------|----------------|")
    w(f"| 生 mean Hamming | {trad_scores['sheng_hamming']:.4f} | {sh_pct:.1f}% | {interp(sh_pct)} |")
    w(f"| 克 mean Hamming | {trad_scores['ke_hamming']:.4f} | {kh_pct:.1f}% | {interp(kh_pct)} |")
    w(f"| 生 complement frac | {trad_scores['sheng_comp_frac']:.4f} | {sc_pct:.1f}% | {interp(sc_pct)} |")
    w(f"| 克 complement frac | {trad_scores['ke_comp_frac']:.4f} | {kc_pct:.1f}% | {interp(kc_pct)} |")
    w(f"| Intra-element Hamming | {trad_scores['intra_hamming']:.4f} | {ih_pct:.1f}% | {interp(ih_pct)} |")
    w("")

    # Distribution summaries
    w(f"### Distribution Summaries\n")
    for label, arr, trad_val in [
        ("生 mean Hamming", all_sheng_h, trad_scores['sheng_hamming']),
        ("克 mean Hamming", all_ke_h, trad_scores['ke_hamming']),
        ("生 complement fraction", all_sheng_comp, trad_scores['sheng_comp_frac']),
        ("克 complement fraction", all_ke_comp, trad_scores['ke_comp_frac']),
        ("Intra-element mean Hamming", all_intra_h, trad_scores['intra_hamming']),
    ]:
        a = np.array(arr)
        w(f"**{label}:** min={a.min():.4f}, max={a.max():.4f}, "
          f"mean={a.mean():.4f}, std={a.std():.4f}, traditional={trad_val:.4f}")
    w("")

    # ASCII histogram for 生 mean Hamming
    w("### Histogram: 生 Mean Hamming Distance\n")
    w("```")
    a = np.array(all_sheng_h)
    bins = np.linspace(a.min() - 0.01, a.max() + 0.01, 21)
    hist, edges = np.histogram(a, bins=bins)
    max_bar = max(hist)
    for i in range(len(hist)):
        lo, hi = edges[i], edges[i + 1]
        bar_len = int(50 * hist[i] / max_bar) if max_bar > 0 else 0
        marker = " ◄ TRAD" if lo <= trad_scores['sheng_hamming'] < hi else ""
        w(f"  {lo:5.2f}-{hi:5.2f} | {'█' * bar_len} {hist[i]}{marker}")
    w("```\n")

    # ASCII histogram for 克 mean Hamming
    w("### Histogram: 克 Mean Hamming Distance\n")
    w("```")
    a = np.array(all_ke_h)
    bins = np.linspace(a.min() - 0.01, a.max() + 0.01, 21)
    hist, edges = np.histogram(a, bins=bins)
    max_bar = max(hist)
    for i in range(len(hist)):
        lo, hi = edges[i], edges[i + 1]
        bar_len = int(50 * hist[i] / max_bar) if max_bar > 0 else 0
        marker = " ◄ TRAD" if lo <= trad_scores['ke_hamming'] < hi else ""
        w(f"  {lo:5.2f}-{hi:5.2f} | {'█' * bar_len} {hist[i]}{marker}")
    w("```\n")

    # ══════════════════════════════════════════════════════════════════════
    # Structural Analysis
    # ══════════════════════════════════════════════════════════════════════
    w("## Structural Analysis\n")

    w("### Observation 1: 体/用 Hamming is EXACTLY the baseline (theorem)\n")
    w(f"The 体/用 Hamming distribution is identical to the baseline 8×8 distribution.")
    w("This is not empirical — it is a structural theorem: each hexagram contributes 3 copies")
    w("of (upper, lower) and 3 copies of (lower, upper), so over all 64 hexagrams, every ordered")
    w("trigram pair (a, b) appears exactly 6 times. The 体/用 decomposition samples ALL trigram")
    w("pairs uniformly. The five-phase evaluation layer operates on a perfectly representative")
    w("sample — no bias toward opposition or similarity.\n")

    w("### Observation 2: Intra-element Hamming structure\n")
    for e, d in intra.items():
        w(f"- {e}: {fmt3(d['a'])} ⊕ {fmt3(d['b'])} = {fmt3(d['xor'])}, d={d['hamming']}")
    w("")
    w("Metal and Earth pair trigrams at d=1 (minimal perturbation); Wood pairs at d=3 (complement).")
    w(f"Traditional intra-element mean Hamming = {trad_scores['intra_hamming']:.4f}.\n")

    w("### Observation 3: 生 vs 克 Hamming profiles\n")
    w(f"生 mean: {sh_mean:.4f}, 克 mean: {kh_mean:.4f}")
    w(f"Difference: {abs(sh_mean - kh_mean):.4f}.")
    if abs(sh_mean - kh_mean) > 0.1:
        w(f"生 edges connect more Hamming-distant trigrams than 克 edges.\n")
    else:
        w("Both generation and overcoming span similar Hamming distances.\n")

    w("### Observation 4: Traditional assignment ranking\n")
    w(f"Among {n_assign} valid assignments:")
    w(f"- 生 Hamming: percentile {sh_pct:.1f}%")
    w(f"- 克 Hamming: percentile {kh_pct:.1f}%")
    w(f"- 生 complement frac: percentile {sc_pct:.1f}%")
    w(f"- 克 complement frac: percentile {kc_pct:.1f}%")
    w(f"- Intra-element Hamming: percentile {ih_pct:.1f}%\n")

    pcts = [sh_pct, kh_pct, sc_pct, kc_pct, ih_pct]
    extreme = any(p < 5 or p > 95 for p in pcts)
    if extreme:
        w("The traditional assignment is **extreme** on at least one metric —")
        w("it is NOT a random choice from the space of valid assignments.\n")
    else:
        moderate = any(p < 25 or p > 75 for p in pcts)
        if moderate:
            w("The traditional assignment is **moderately unusual** on some metrics —")
            w("not random but not maximally extreme either.\n")
        else:
            w("The traditional assignment is **unremarkable** on all metrics —")
            w("consistent with being chosen by criteria unrelated to Hamming structure.\n")

    return '\n'.join(lines)


# ─── Main ────────────────────────────────────────────────────────────────────

def main():
    print("=" * 70)
    print("PHASE 4: 生克 (SHĒNG-KÈ) FOUNDATION DATA")
    print("=" * 70)

    # ── Q1 ──
    print("\n── Q1: 体/用 as Scale Bridge ──")
    states = compute_tiyong_states()
    print(f"  Computed {len(states)} 体/用 states")
    tiyong_results = analyze_tiyong(states)

    hd = tiyong_results['hamming_dist']
    total = sum(hd.values())
    print(f"\n  Hamming distribution (体 vs 用):")
    for d in range(4):
        print(f"    d={d}: {hd.get(d, 0)} ({hd.get(d, 0)/total:.4f})")
    mean_hd = sum(d * hd.get(d, 0) for d in range(4)) / total
    bd = tiyong_results['baseline_hamming']
    bd_total = sum(bd.values())
    mean_bd = sum(d * bd.get(d, 0) for d in range(4)) / bd_total
    print(f"  Mean: {mean_hd:.4f} (baseline: {mean_bd:.4f})")

    # ── Q2 ──
    print("\n── Q2: 生克 in Hamming/Mask Terms ──")
    shengke_results = analyze_shengke_structure()

    print("\n  Intra-element Hamming distances:")
    for e, d in shengke_results['intra'].items():
        print(f"    {e}: {fmt3(d['a'])} ⊕ {fmt3(d['b'])} = {fmt3(d['xor'])}, d={d['hamming']}")

    sh = shengke_results['sheng_hamming_dist']
    kh = shengke_results['ke_hamming_dist']
    sh_total = sum(sh.values())
    kh_total = sum(kh.values())
    sh_mean = sum(d * sh.get(d, 0) for d in range(4)) / sh_total
    kh_mean = sum(d * kh.get(d, 0) for d in range(4)) / kh_total
    print(f"\n  生 mean Hamming: {sh_mean:.4f} (n={sh_total} pairs)")
    print(f"  克 mean Hamming: {kh_mean:.4f} (n={kh_total} pairs)")

    # Hamming by relation
    print("\n  Hamming by five-phase relation (excluding self-pairs):")
    rh = shengke_results['rel_hamming']
    for rel in ["比和", "生体", "克体", "体生用", "体克用"]:
        if rel in rh:
            hcounts = rh[rel]
            t = sum(hcounts.values())
            mean = sum(d * hcounts.get(d, 0) for d in range(4)) / t if t > 0 else 0
            print(f"    {rel}: mean={mean:.4f}, n={t}")

    # ── Q6 ──
    print("\n── Q6: Five-Phase Cycle as Combinatorial Object ──")
    print("  Enumerating all valid surjections (partition 2,2,2,1,1)...")
    assignments = enumerate_assignments()
    n_assign = len(assignments)
    print(f"  Total assignments: {n_assign}")

    trad_idx = find_traditional_index(assignments)
    print(f"  Traditional assignment index: {trad_idx}")

    print("  Scoring all assignments...")
    all_scores = []
    for m in assignments:
        all_scores.append(score_assignment(m))

    trad_scores = all_scores[trad_idx]
    all_sheng_h = [s['sheng_hamming'] for s in all_scores]
    all_ke_h = [s['ke_hamming'] for s in all_scores]
    all_sheng_comp = [s['sheng_comp_frac'] for s in all_scores]
    all_ke_comp = [s['ke_comp_frac'] for s in all_scores]
    all_intra_h = [s['intra_hamming'] for s in all_scores]

    print(f"\n  Traditional scores:")
    print(f"    生 mean Hamming: {trad_scores['sheng_hamming']:.4f}")
    print(f"    克 mean Hamming: {trad_scores['ke_hamming']:.4f}")
    print(f"    生 complement frac: {trad_scores['sheng_comp_frac']:.4f}")
    print(f"    克 complement frac: {trad_scores['ke_comp_frac']:.4f}")
    print(f"    Intra-element Hamming: {trad_scores['intra_hamming']:.4f}")

    a_sh = np.array(all_sheng_h)
    a_kh = np.array(all_ke_h)
    a_sc = np.array(all_sheng_comp)
    a_kc = np.array(all_ke_comp)
    a_ih = np.array(all_intra_h)

    def pct(arr, val):
        return 100.0 * np.sum(arr <= val) / len(arr)

    print(f"\n  Percentile rankings:")
    print(f"    生 Hamming: {pct(a_sh, trad_scores['sheng_hamming']):.1f}%")
    print(f"    克 Hamming: {pct(a_kh, trad_scores['ke_hamming']):.1f}%")
    print(f"    生 complement frac: {pct(a_sc, trad_scores['sheng_comp_frac']):.1f}%")
    print(f"    克 complement frac: {pct(a_kc, trad_scores['ke_comp_frac']):.1f}%")
    print(f"    Intra-element Hamming: {pct(a_ih, trad_scores['intra_hamming']):.1f}%")

    print(f"\n  Distribution ranges:")
    print(f"    生 Hamming: [{a_sh.min():.4f}, {a_sh.max():.4f}], mean={a_sh.mean():.4f}")
    print(f"    克 Hamming: [{a_kh.min():.4f}, {a_kh.max():.4f}], mean={a_kh.mean():.4f}")
    print(f"    Intra-element: [{a_ih.min():.4f}, {a_ih.max():.4f}], mean={a_ih.mean():.4f}")

    # ── Write markdown ──
    q6_data = {
        'n_assignments': n_assign,
        'trad_idx': trad_idx,
        'trad_scores': trad_scores,
        'all_sheng_hamming': all_sheng_h,
        'all_ke_hamming': all_ke_h,
        'all_sheng_comp': all_sheng_comp,
        'all_ke_comp': all_ke_comp,
        'all_intra_hamming': all_intra_h,
    }

    md = format_markdown(states, tiyong_results, shengke_results, q6_data)
    out_path = Path(__file__).parent / "foundation_results.md"
    out_path.write_text(md)
    print(f"\nResults written to {out_path}")


if __name__ == '__main__':
    main()
