"""
What properties do the different groups generated by FPF triples have?

Groups that appear:
- S₄ (order 24) — from (0,0,1), (0,1,1), (1,1,1), (1,1,2)
- PSL(2,7) (order 168) — from (0,0,0), (0,0,1), (0,1,1)
- Order 48 — from (0,0,1), (0,1,2)
- A₄ (order 12) — from (1,2,2)
- D₄ (order 8) — from (0,0,0), (0,0,2), (0,2,2), (2,2,2)
- S₃ (order 6) — from (1,1,1)
- V₄ (order 4) — from (0,0,0)
- Order 16, 32, 64 — from (0,0,0), (0,0,2)

For each: what is the group, what does it do to 8 elements,
does it have block structure, what kind of pairings does it support?
"""

from itertools import combinations
from collections import Counter, defaultdict

N = 8

def generate_fpf_involutions(n):
    if n == 0:
        yield {}
        return
    first = 0
    for partner in range(1, n):
        remaining = [x for x in range(n) if x != first and x != partner]
        for sub in _fpf_helper(remaining):
            inv = dict(sub)
            inv[first] = partner
            inv[partner] = first
            yield inv

def _fpf_helper(elems):
    if len(elems) == 0:
        yield {}
        return
    first = elems[0]
    rest = elems[1:]
    for i, partner in enumerate(rest):
        remaining = rest[:i] + rest[i+1:]
        for sub in _fpf_helper(remaining):
            inv = dict(sub)
            inv[first] = partner
            inv[partner] = first
            yield inv

fpf_list = list(generate_fpf_involutions(N))

def overlap(inv1, inv2):
    def pairs(inv):
        return {frozenset([a, b]) for a, b in inv.items() if a < b}
    return len(pairs(inv1) & pairs(inv2))

def compose(p1, p2):
    return {k: p2[p1[k]] for k in p1}

def commutes(i1, i2):
    return compose(i1, i2) == compose(i2, i1)

def group_generated_by(gens, max_size=10000):
    def to_tuple(inv):
        return tuple(inv[i] for i in range(N))
    identity = tuple(range(N))
    group = {identity}
    queue = [to_tuple(g) for g in gens]
    group.update(queue)
    while queue:
        new = []
        for g in queue:
            g_dict = {i: g[i] for i in range(N)}
            for gen in gens:
                prod = tuple(gen[g[i]] for i in range(N))
                if prod not in group:
                    group.add(prod)
                    new.append(prod)
                    if len(group) > max_size:
                        return group
                prod2 = tuple(g[gen[i]] for i in range(N))
                if prod2 not in group:
                    group.add(prod2)
                    new.append(prod2)
                    if len(group) > max_size:
                        return group
        queue = new
    return group

def cycle_type(perm):
    """Get cycle type of a permutation (as sorted tuple of cycle lengths)."""
    if isinstance(perm, tuple):
        perm = {i: perm[i] for i in range(len(perm))}
    seen = set()
    cycles = []
    for i in range(N):
        if i in seen:
            continue
        cycle = []
        j = i
        while j not in seen:
            seen.add(j)
            cycle.append(j)
            j = perm[j]
        cycles.append(len(cycle))
    return tuple(sorted(cycles, reverse=True))

def has_block_system(group, block_size=2):
    """Check if group preserves a partition into blocks of given size."""
    # Try all partitions into blocks of block_size
    from itertools import combinations
    
    elements = list(range(N))
    num_blocks = N // block_size
    
    # Generate all partitions into blocks of 2
    def partitions(elems):
        if len(elems) == 0:
            yield []
            return
        first = elems[0]
        for i, partner in enumerate(elems[1:], 1):
            rest = elems[1:i] + elems[i+1:]
            for sub in partitions(rest):
                yield [frozenset([first, partner])] + sub
    
    preserved_count = 0
    total_partitions = 0
    preserved_partitions = []
    
    for partition in partitions(elements):
        total_partitions += 1
        partition_set = frozenset(partition)
        
        # Check if every group element preserves this partition
        preserved = True
        for perm in group:
            if isinstance(perm, tuple):
                perm_dict = {i: perm[i] for i in range(N)}
            else:
                perm_dict = perm
            
            new_blocks = []
            for block in partition:
                new_block = frozenset(perm_dict[x] for x in block)
                new_blocks.append(new_block)
            
            if frozenset(new_blocks) != partition_set:
                preserved = False
                break
        
        if preserved:
            preserved_count += 1
            if preserved_count <= 5:
                preserved_partitions.append(partition)
    
    return preserved_count, total_partitions, preserved_partitions

def count_fpf_in_group(group):
    """Count fixed-point-free elements."""
    count = 0
    for perm in group:
        if isinstance(perm, tuple):
            if all(perm[i] != i for i in range(N)):
                count += 1
        else:
            if all(perm[i] != i for i in perm):
                count += 1
    return count

def count_involutions_in_group(group):
    """Count involutions (order 2 elements)."""
    identity = tuple(range(N))
    count = 0
    fpf_inv = 0
    for perm in group:
        if perm == identity:
            continue
        # Check if order 2
        if isinstance(perm, tuple):
            perm_dict = {i: perm[i] for i in range(N)}
            comp = tuple(perm_dict[perm_dict[i]] for i in range(N))
        if comp == identity:
            count += 1
            if all(perm[i] != i for i in range(N)):
                fpf_inv += 1
    return count, fpf_inv


# ══════════════════════════════════════════════════════════════════════════════
# Collect one example of each group from each overlap pattern
# ══════════════════════════════════════════════════════════════════════════════

print("Collecting examples of each group type...")

examples = {}  # (overlap_pattern, group_size) → (generators, group)

for i, a in enumerate(fpf_list):
    if i % 10 == 0:
        print(f"  scanning involution {i}/105...", end='\r')
    for j, b in enumerate(fpf_list):
        if j <= i:
            continue
        ov_ab = overlap(a, b)
        for k, c in enumerate(fpf_list):
            if k <= j:
                continue
            ov_ac = overlap(a, c)
            ov_bc = overlap(b, c)
            pattern = tuple(sorted([ov_ab, ov_ac, ov_bc]))
            
            grp = group_generated_by([a, b, c])
            gs = len(grp)
            
            key = (pattern, gs)
            if key not in examples:
                examples[key] = ([a, b, c], grp)

print(f"\n  Found {len(examples)} distinct (pattern, group_size) pairs")

# ══════════════════════════════════════════════════════════════════════════════
# Analyze each group
# ══════════════════════════════════════════════════════════════════════════════

print("\n" + "=" * 70)
print("GROUP PROPERTIES")
print("=" * 70)

# Group by group size
by_size = defaultdict(list)
for (pattern, gs), (gens, grp) in examples.items():
    by_size[gs].append((pattern, gens, grp))

for gs in sorted(by_size.keys()):
    items = by_size[gs]
    patterns = sorted(set(pat for pat, _, _ in items))
    
    # Use first example for analysis
    _, gens, grp = items[0]
    
    print(f"\n{'─' * 70}")
    print(f"ORDER {gs} — appears in overlap patterns: {patterns}")
    print(f"{'─' * 70}")
    
    # Cycle type distribution
    ct_dist = Counter()
    for perm in grp:
        ct_dist[cycle_type(perm)] += 1
    
    print(f"\n  Cycle type distribution:")
    for ct, count in sorted(ct_dist.items(), key=lambda x: -x[1]):
        ct_str = ','.join(str(c) for c in ct)
        fpf = all(c > 1 for c in ct)
        tag = " [FPF]" if fpf else ""
        print(f"    ({ct_str}): {count}{tag}")
    
    # Count FPF elements and involutions
    n_involutions, n_fpf_inv = count_involutions_in_group(grp)
    n_fpf = count_fpf_in_group(grp)
    print(f"\n  FPF elements: {n_fpf}/{gs} ({100*n_fpf/gs:.0f}%)")
    print(f"  Involutions: {n_involutions}/{gs}")
    print(f"  FPF involutions: {n_fpf_inv}/{gs}")
    
    # Block systems
    n_preserved, n_total, preserved = has_block_system(grp)
    print(f"\n  Block systems (4 blocks of 2): {n_preserved}/{n_total} preserved")
    if preserved:
        for partition in preserved[:3]:
            blocks_str = ' '.join('{' + ','.join(str(x) for x in sorted(b)) + '}' for b in partition)
            print(f"    {blocks_str}")
    
    # Transitivity
    # Check if the group acts transitively on {0,...,7}
    orbit = {0}
    for perm in grp:
        if isinstance(perm, tuple):
            orbit.add(perm[0])
    transitive = len(orbit) == N
    print(f"\n  Transitive on 8 elements: {transitive} (orbit of 0: size {len(orbit)})")
    
    # Primitivity (if transitive): are there non-trivial block systems?
    if transitive:
        if n_preserved > 1:  # more than just the trivial partition
            print(f"  Imprimitive (has non-trivial block systems)")
        else:
            print(f"  Primitive (no non-trivial block systems)")

# ══════════════════════════════════════════════════════════════════════════════
# Key comparison: S₄ (Rep A) vs S₄ (Rep B)
# ══════════════════════════════════════════════════════════════════════════════

print(f"\n{'=' * 70}")
print(f"S₄ REP A vs REP B COMPARISON")
print(f"{'=' * 70}")

# Get one Rep A example (from (0,0,1) with commutation)
# and one Rep B example (from (1,1,2))
rep_a = None
rep_b = None

for (pattern, gs), (gens, grp) in examples.items():
    if gs == 24 and pattern == (0, 0, 1) and rep_a is None:
        # Check if it has commutation (Rep A)
        a, b, c = gens
        ov_ab, ov_ac, ov_bc = overlap(a,b), overlap(a,c), overlap(b,c)
        # Find zero-overlap pairs
        has_comm = False
        if ov_ab == 0 and commutes(a, b): has_comm = True
        if ov_ac == 0 and commutes(a, c): has_comm = True
        if ov_bc == 0 and commutes(b, c): has_comm = True
        if has_comm:
            rep_a = (gens, grp)
    if gs == 24 and pattern == (1, 1, 2) and rep_b is None:
        rep_b = (gens, grp)

if rep_a and rep_b:
    for name, (gens, grp) in [("Rep A (0,0,1)+comm", rep_a), ("Rep B (1,1,2)", rep_b)]:
        print(f"\n  {name}:")
        
        ct_dist = Counter()
        for perm in grp:
            ct_dist[cycle_type(perm)] += 1
        
        print(f"    Cycle types:")
        for ct, count in sorted(ct_dist.items(), key=lambda x: -x[1]):
            ct_str = ','.join(str(c) for c in ct)
            fpf = all(c > 1 for c in ct)
            tag = " [FPF]" if fpf else ""
            print(f"      ({ct_str}): {count}{tag}")
        
        n_inv, n_fpf_inv = count_involutions_in_group(grp)
        n_fpf = count_fpf_in_group(grp)
        print(f"    FPF elements: {n_fpf}/24")
        print(f"    FPF involutions: {n_fpf_inv}")
        
        n_blocks, _, blocks = has_block_system(grp)
        print(f"    Block systems: {n_blocks}")
        for partition in blocks[:3]:
            blocks_str = ' '.join('{' + ','.join(str(x) for x in sorted(b)) + '}' for b in partition)
            print(f"      {blocks_str}")
        
        # Show the three generators' pairings
        print(f"    Generator pairings:")
        for gi, g in enumerate(gens):
            pairs = []
            seen = set()
            for x in range(N):
                if x not in seen:
                    pairs.append(f"{x}↔{g[x]}")
                    seen.add(x)
                    seen.add(g[x])
            ov_info = [overlap(g, gens[j]) for j in range(3) if j != gi]
            print(f"      ι{gi+1}: {', '.join(pairs)}  overlaps={ov_info}")

# ══════════════════════════════════════════════════════════════════════════════
# PSL(2,7) — the main competitor
# ══════════════════════════════════════════════════════════════════════════════

print(f"\n{'=' * 70}")
print(f"PSL(2,7) — THE MAIN COMPETITOR")
print(f"{'=' * 70}")

psl_example = None
for (pattern, gs), (gens, grp) in examples.items():
    if gs == 168:
        psl_example = (pattern, gens, grp)
        break

if psl_example:
    pattern, gens, grp = psl_example
    print(f"\n  From overlap pattern {pattern}")
    
    ct_dist = Counter()
    for perm in grp:
        ct_dist[cycle_type(perm)] += 1
    
    print(f"  Cycle types:")
    for ct, count in sorted(ct_dist.items(), key=lambda x: -x[1]):
        ct_str = ','.join(str(c) for c in ct)
        fpf = all(c > 1 for c in ct)
        tag = " [FPF]" if fpf else ""
        print(f"    ({ct_str}): {count}{tag}")
    
    n_inv, n_fpf_inv = count_involutions_in_group(grp)
    n_fpf = count_fpf_in_group(grp)
    print(f"\n  FPF elements: {n_fpf}/168 ({100*n_fpf/168:.0f}%)")
    print(f"  FPF involutions: {n_fpf_inv}")
    
    n_blocks, _, blocks = has_block_system(grp)
    print(f"  Block systems (4×2): {n_blocks}")
    
    orbit = {0}
    for perm in grp:
        if isinstance(perm, tuple):
            orbit.add(perm[0])
    print(f"  Transitive: {len(orbit) == N}")
    if n_blocks == 0:
        print(f"  Primitive: YES (no block systems)")
    
    print(f"\n  KEY DIFFERENCE: PSL(2,7) is SIMPLE (no normal subgroups).")
    print(f"  S₄ has the normal chain S₄ ⊃ A₄ ⊃ V₄ ⊃ {{id}}.")
    print(f"  PSL(2,7) has no substructure — it's indivisible.")
    print(f"  No block decomposition means no 'types' or 'categories'.")
    print(f"  You get a rich group but no way to organize the 8 elements")
    print(f"  into meaningful subsets.")
