#!/usr/bin/env python3
"""
Round 2: Resolve the 六合 question

Three computations on the 六合-induced edge set:
1. Composition with existing involutions / extension to full involution
2. Bipartition identification and comparison with known partitions
3. Degree-2 vs degree-1 classification
"""

from itertools import combinations

# ═══════════════════════════════════════════════════════════════
# REFERENCE DATA
# ═══════════════════════════════════════════════════════════════

TRIGRAMS = ['Kun', 'Zhen', 'Gen', 'Dui', 'Kan', 'Li', 'Xun', 'Qian']

BINARY = {
    'Kun': '000', 'Zhen': '100', 'Gen': '001', 'Dui': '110',
    'Kan': '010', 'Li': '101', 'Xun': '011', 'Qian': '111'
}

BLOCKS = [
    frozenset({'Kun', 'Zhen'}),    # block 0
    frozenset({'Gen', 'Dui'}),     # block 1
    frozenset({'Kan', 'Li'}),      # block 2
    frozenset({'Xun', 'Qian'})     # block 3
]

P_PLUS  = frozenset({'Kan', 'Zhen', 'Dui', 'Li'})    # Lo Shu odd, cardinal
P_MINUS = frozenset({'Kun', 'Gen', 'Qian', 'Xun'})    # Lo Shu even, intercardinal

IOTA1 = {frozenset({'Qian', 'Kun'}), frozenset({'Dui', 'Gen'}),
         frozenset({'Li', 'Kan'}), frozenset({'Xun', 'Zhen'})}
IOTA2 = {frozenset({'Li', 'Kan'}), frozenset({'Kun', 'Gen'}),
         frozenset({'Zhen', 'Dui'}), frozenset({'Xun', 'Qian'})}
IOTA3 = {frozenset({'Kan', 'Qian'}), frozenset({'Kun', 'Dui'}),
         frozenset({'Zhen', 'Gen'}), frozenset({'Xun', 'Li'})}
TAU =   {frozenset({'Kun', 'Zhen'}), frozenset({'Gen', 'Dui'}),
         frozenset({'Kan', 'Li'}), frozenset({'Xun', 'Qian'})}

KNOWN_INVOLUTIONS = {
    'ι₁ (Fu Xi)': IOTA1,
    'ι₂ (KW)': IOTA2,
    'ι₃ (He Tu)': IOTA3,
    'τ (ι₂∘ι₃)': TAU,
}

# 六合 edges on trigrams (from Round 1)
LIUHE_EDGES = [
    (frozenset({'Kan', 'Gen'}), 'Earth'),      # 子丑
    (frozenset({'Gen', 'Qian'}), 'Wood'),       # 寅亥
    (frozenset({'Zhen', 'Qian'}), 'Fire'),      # 卯戌
    (frozenset({'Xun', 'Dui'}), 'Metal'),       # 辰酉
    (frozenset({'Xun', 'Kun'}), 'Water'),       # 巳申
    (frozenset({'Li', 'Kun'}), 'Fire'),          # 午未
]
LIUHE_PAIRS = set(p for p, _ in LIUHE_EDGES)

# Build adjacency for 六合
ADJ = {t: set() for t in TRIGRAMS}
for pair, _ in LIUHE_EDGES:
    a, b = list(pair)
    ADJ[a].add(b)
    ADJ[b].add(a)

# Helper: convert involution (set of frozenset pairs) to dict permutation
def inv_to_perm(inv):
    perm = {}
    for pair in inv:
        a, b = list(pair)
        perm[a] = b
        perm[b] = a
    return perm

# Helper: apply permutation to a trigram
def apply_perm(perm, t):
    return perm[t]

# Enumerate all 24 elements of S₄ acting on 8 trigrams
# (the group generated by ι₁, ι₂, ι₃)
def generate_group():
    """Generate ⟨ι₁, ι₂, ι₃⟩ as permutations on 8 trigrams."""
    perms = set()
    # Represent permutations as tuples (images of Kun,Zhen,Gen,Dui,Kan,Li,Xun,Qian)
    idx = {t: i for i, t in enumerate(TRIGRAMS)}
    
    def perm_to_tuple(p):
        return tuple(p[t] for t in TRIGRAMS)
    
    def compose(p1, p2):
        return {t: p1[p2[t]] for t in TRIGRAMS}
    
    identity = {t: t for t in TRIGRAMS}
    generators = [inv_to_perm(IOTA1), inv_to_perm(IOTA2), inv_to_perm(IOTA3)]
    
    # BFS closure
    queue = [identity] + generators
    seen = {perm_to_tuple(identity)}
    for g in generators:
        seen.add(perm_to_tuple(g))
    
    while queue:
        p = queue.pop(0)
        for g in generators:
            for new in [compose(p, g), compose(g, p)]:
                t = perm_to_tuple(new)
                if t not in seen:
                    seen.add(t)
                    queue.append(new)
    
    # Convert back to list of dicts
    result = []
    for t in seen:
        perm = {TRIGRAMS[i]: t[i] for i in range(8)}
        result.append(perm)
    return result

# All involution edges
ALL_INV_EDGES = IOTA1 | IOTA2 | IOTA3 | TAU

# Unclaimed edges (neither in any involution nor in 六合)
ALL_EDGES = set(frozenset({a, b}) for a, b in combinations(TRIGRAMS, 2))
UNCLAIMED = ALL_EDGES - ALL_INV_EDGES - LIUHE_PAIRS


# ═══════════════════════════════════════════════════════════════
# COMPUTATION 1: Composition & Extension
# ═══════════════════════════════════════════════════════════════

print("=" * 70)
print("COMPUTATION 1: Composition with involutions & Extension to involution")
print("=" * 70)

print("\n--- 1a: Relational composition ι ∘ 六合 ---")
print("(Apply 六合 as relation first, then ι as permutation)")
print()

for inv_name, inv in KNOWN_INVOLUTIONS.items():
    perm = inv_to_perm(inv)
    # For each trigram x, compute {ι(y) : y ∈ 六合(x)}
    # where 六合(x) = set of 六合-neighbors of x
    composed = {}
    for t in TRIGRAMS:
        images = set()
        for neighbor in ADJ[t]:
            images.add(perm[neighbor])
        composed[t] = images
    
    print(f"  {inv_name} ∘ 六合:")
    for t in TRIGRAMS:
        imgs = sorted(composed[t])
        print(f"    {t:>5} → {imgs}")
    
    # Check if this is a clean matching (each node maps to exactly 1 other)
    is_function = all(len(v) <= 1 for v in composed.values())
    is_total = all(len(v) >= 1 for v in composed.values())
    
    if is_function and is_total:
        # It's a permutation! Check if involution
        perm_result = {t: next(iter(v)) for t, v in composed.items()}
        is_invol = all(perm_result[perm_result[t]] == t for t in TRIGRAMS)
        is_fpf = all(perm_result[t] != t for t in TRIGRAMS)
        print(f"    → IS a function! Involution={is_invol}, FPF={is_fpf}")
    else:
        multi = {t: v for t, v in composed.items() if len(v) > 1}
        empty = {t: v for t, v in composed.items() if len(v) == 0}
        if multi:
            print(f"    → NOT a function (multi-valued: {list(multi.keys())})")
        if empty:
            print(f"    → NOT total (unmapped: {list(empty.keys())})")
    
    # Also try the reverse: 六合 ∘ ι
    composed_rev = {}
    for t in TRIGRAMS:
        it = perm[t]  # apply ι first
        composed_rev[t] = set(ADJ[it])  # then 六合 neighbors
    
    is_function_rev = all(len(v) <= 1 for v in composed_rev.values())
    is_total_rev = all(len(v) >= 1 for v in composed_rev.values())
    
    if is_function_rev and is_total_rev:
        perm_rev = {t: next(iter(v)) for t, v in composed_rev.items()}
        is_invol_rev = all(perm_rev[perm_rev[t]] == t for t in TRIGRAMS)
        is_fpf_rev = all(perm_rev[t] != t for t in TRIGRAMS)
        print(f"    六合 ∘ {inv_name}: IS a function! Involution={is_invol_rev}, FPF={is_fpf_rev}")
    print()


print("\n--- 1b: Extension of 六合 to a full FPF involution ---")
print("六合 has 6 edges. A full FPF involution needs exactly 4 disjoint edges")
print("covering all 8 trigrams. 六合 has too many edges (6), not a matching.")
print()
print("But: can we find a 4-edge subset of 六合's 6 edges that is a perfect matching?")
print()

# Find all perfect matchings within the 六合 edge set
liuhe_list = list(LIUHE_PAIRS)
perfect_matchings = []

for combo in combinations(range(len(liuhe_list)), 4):
    edges = [liuhe_list[i] for i in combo]
    # Check if these 4 edges form a perfect matching (all 8 trigrams, each once)
    covered = set()
    valid = True
    for e in edges:
        for t in e:
            if t in covered:
                valid = False
                break
            covered.add(t)
        if not valid:
            break
    if valid and len(covered) == 8:
        perfect_matchings.append(set(edges))

print(f"Perfect matchings within 六合's 6 edges: {len(perfect_matchings)}")
for i, m in enumerate(perfect_matchings):
    print(f"\n  Matching {i+1}:")
    for p in sorted(m, key=lambda x: sorted(x)):
        a, b = sorted(p)
        print(f"    {a} ↔ {b}")
    
    # Check against known involutions
    for name, inv in KNOWN_INVOLUTIONS.items():
        if m == inv:
            print(f"    → MATCHES {name}")
            break
    else:
        print(f"    → NEW (not any known involution)")
    
    # Check if it's in the S₄ group
    # Convert to permutation and check
    perm = {}
    for p in m:
        a, b = list(p)
        perm[a] = b
        perm[b] = a
    # Check if this perm is in ⟨ι₁, ι₂, ι₃⟩
    group = generate_group()
    in_group = any(all(g[t] == perm[t] for t in TRIGRAMS) for g in group)
    print(f"    In ⟨ι₁, ι₂, ι₃⟩ = S₄? {'YES' if in_group else 'NO'}")


# Alternative: extend 六合 by adding 1 edge from unclaimed
print("\n\n--- 1c: Extending 六合 with 1 unclaimed edge ---")
print(f"Unclaimed edges: {len(UNCLAIMED)}")
for e in sorted(UNCLAIMED, key=lambda x: sorted(x)):
    a, b = sorted(e)
    bl_a = next(i for i, bl in enumerate(BLOCKS) if a in bl)
    bl_b = next(i for i, bl in enumerate(BLOCKS) if b in bl)
    print(f"  {a}↔{b} (block {bl_a}↔{bl_b})")

# For each unclaimed edge, check if adding it to some 3-edge subset of 六合
# produces a perfect matching
print("\nSearching for (3 edges from 六合) + (1 unclaimed edge) = perfect matching...")

extended_matchings = []
for ue in UNCLAIMED:
    for combo in combinations(range(len(liuhe_list)), 3):
        edges = [liuhe_list[i] for i in combo] + [ue]
        covered = set()
        valid = True
        for e in edges:
            for t in e:
                if t in covered:
                    valid = False
                    break
                covered.add(t)
            if not valid:
                break
        if valid and len(covered) == 8:
            extended_matchings.append((set(edges), ue))

print(f"Extended matchings found: {len(extended_matchings)}")
for i, (m, added) in enumerate(extended_matchings):
    a_add, b_add = sorted(added)
    print(f"\n  Extended matching {i+1} (added {a_add}↔{b_add}):")
    for p in sorted(m, key=lambda x: sorted(x)):
        a, b = sorted(p)
        marker = " ← added" if p == added else ""
        print(f"    {a} ↔ {b}{marker}")
    
    for name, inv in KNOWN_INVOLUTIONS.items():
        if m == inv:
            print(f"    → MATCHES {name}")
            break
    else:
        # Check S₄ membership
        perm = {}
        for p in m:
            a, b = list(p)
            perm[a] = b
            perm[b] = a
        group = generate_group()
        in_group = any(all(g[t] == perm[t] for t in TRIGRAMS) for g in group)
        print(f"    → {'In S₄ group' if in_group else 'NOT in S₄ group'}")


# ═══════════════════════════════════════════════════════════════
# COMPUTATION 2: Bipartition analysis
# ═══════════════════════════════════════════════════════════════

print("\n\n" + "=" * 70)
print("COMPUTATION 2: 六合 bipartition analysis")
print("=" * 70)

# 2-color the 六合 graph
color = {}
queue = [TRIGRAMS[0]]
color[TRIGRAMS[0]] = 0
while queue:
    node = queue.pop(0)
    for neighbor in ADJ[node]:
        if neighbor not in color:
            color[neighbor] = 1 - color[node]
            queue.append(neighbor)

# Handle disconnected components
for t in TRIGRAMS:
    if t not in color:
        print(f"  WARNING: {t} not reached by BFS — disconnected component")
        # Assign arbitrarily
        color[t] = 0

side_A = frozenset(t for t, c in color.items() if c == 0)
side_B = frozenset(t for t, c in color.items() if c == 1)

print(f"\n六合 bipartition:")
print(f"  Side A: {sorted(side_A)}")
print(f"  Side B: {sorted(side_B)}")

# Check connectivity first
print(f"\n  Is the graph connected?")
visited = set()
stack = [TRIGRAMS[0]]
while stack:
    node = stack.pop()
    if node in visited:
        continue
    visited.add(node)
    for n in ADJ[node]:
        if n not in visited:
            stack.append(n)

if visited == set(TRIGRAMS):
    print(f"  YES — all 8 trigrams reached from {TRIGRAMS[0]}")
    print(f"  → Bipartition is UNIQUE (up to swapping sides)")
else:
    unreached = set(TRIGRAMS) - visited
    print(f"  NO — unreached: {sorted(unreached)}")
    print(f"  → Bipartition is NOT unique (disconnected components can be colored either way)")
    
    # Find connected components
    components = []
    remaining = set(TRIGRAMS)
    while remaining:
        start = next(iter(remaining))
        comp = set()
        stack = [start]
        while stack:
            node = stack.pop()
            if node in comp:
                continue
            comp.add(node)
            remaining.discard(node)
            for n in ADJ[node]:
                if n not in comp:
                    stack.append(n)
        components.append(comp)
    
    print(f"  Connected components: {len(components)}")
    for i, comp in enumerate(components):
        print(f"    Component {i}: {sorted(comp)}")
    
    print(f"\n  Number of valid 2-colorings: 2^{len(components)} = {2**len(components)}")
    print(f"  (each disconnected component can independently flip)")

# Now systematically check all possible bipartitions
print(f"\n--- Comparison with known partitions ---")

# Generate all valid bipartitions (for disconnected graph)
# A bipartition is valid if all 六合 edges cross between sides
from itertools import product

if len(components) > 1:
    # For each component, we know the internal 2-coloring
    # We can flip entire components
    comp_colorings = []
    for comp in components:
        c0 = frozenset(t for t in comp if color[t] == 0)
        c1 = frozenset(t for t in comp if color[t] == 1)
        comp_colorings.append((c0, c1))
    
    # Generate all 2^n_components bipartitions
    all_bipartitions = set()
    for flips in product([0, 1], repeat=len(components)):
        side_a = set()
        side_b = set()
        for i, flip in enumerate(flips):
            c0, c1 = comp_colorings[i]
            if flip == 0:
                side_a |= c0
                side_b |= c1
            else:
                side_a |= c1
                side_b |= c0
        # Normalize: put lexicographically smaller side first
        side_a, side_b = frozenset(side_a), frozenset(side_b)
        bp = frozenset({side_a, side_b})
        all_bipartitions.add(bp)
    
    print(f"\nAll valid bipartitions of the 六合 graph ({len(all_bipartitions)} total):")
else:
    all_bipartitions = {frozenset({side_A, side_B})}
    print(f"\nUnique bipartition:")

# Known partitions to check against
known_partitions = {
    'P₊/P₋ (polarity)': frozenset({P_PLUS, P_MINUS}),
    'B01/B23 (blocks 0,1 vs 2,3)': frozenset({
        frozenset(BLOCKS[0] | BLOCKS[1]),
        frozenset(BLOCKS[2] | BLOCKS[3])
    }),
    'B02/B13 (blocks 0,2 vs 1,3)': frozenset({
        frozenset(BLOCKS[0] | BLOCKS[2]),
        frozenset(BLOCKS[1] | BLOCKS[3])
    }),
    'B03/B12 (blocks 0,3 vs 1,2)': frozenset({
        frozenset(BLOCKS[0] | BLOCKS[3]),
        frozenset(BLOCKS[1] | BLOCKS[2])
    }),
    'Yang-count parity (even/odd)': frozenset({
        frozenset(t for t in TRIGRAMS if BINARY[t].count('1') % 2 == 0),
        frozenset(t for t in TRIGRAMS if BINARY[t].count('1') % 2 == 1)
    }),
}

for bp in sorted(all_bipartitions, key=lambda x: sorted(sorted(s) for s in x)):
    sides = sorted(bp, key=lambda s: sorted(s))
    s1, s2 = sorted(sides[0]), sorted(sides[1])
    print(f"\n  {s1} | {s2}")
    
    bp_set = frozenset({frozenset(s1), frozenset(s2)})
    
    for name, known in known_partitions.items():
        if bp_set == known:
            print(f"    ★ MATCHES: {name}")
    
    # Check if it matches none
    matches = [name for name, known in known_partitions.items() if bp_set == known]
    if not matches:
        print(f"    → No match with any known partition")


# ═══════════════════════════════════════════════════════════════
# COMPUTATION 3: Degree-2 vs Degree-1 analysis
# ═══════════════════════════════════════════════════════════════

print("\n\n" + "=" * 70)
print("COMPUTATION 3: Degree analysis")
print("=" * 70)

deg2 = frozenset(t for t in TRIGRAMS if len(ADJ[t]) == 2)
deg1 = frozenset(t for t in TRIGRAMS if len(ADJ[t]) == 1)
deg0 = frozenset(t for t in TRIGRAMS if len(ADJ[t]) == 0)

print(f"\nDegree-2 trigrams: {sorted(deg2)}")
print(f"Degree-1 trigrams: {sorted(deg1)}")
if deg0:
    print(f"Degree-0 trigrams: {sorted(deg0)}")

print(f"\nDegree-2 details:")
for t in sorted(deg2):
    yang_count = BINARY[t].count('1')
    block = next(i for i, bl in enumerate(BLOCKS) if t in bl)
    in_p = 'P₊' if t in P_PLUS else 'P₋'
    neighbors = sorted(ADJ[t])
    print(f"  {t:>5}: binary={BINARY[t]}, yang={yang_count}, block={block}, {in_p}, neighbors={neighbors}")

print(f"\nDegree-1 details:")
for t in sorted(deg1):
    yang_count = BINARY[t].count('1')
    block = next(i for i, bl in enumerate(BLOCKS) if t in bl)
    in_p = 'P₊' if t in P_PLUS else 'P₋'
    neighbors = sorted(ADJ[t])
    print(f"  {t:>5}: binary={BINARY[t]}, yang={yang_count}, block={block}, {in_p}, neighbors={neighbors}")

# Check correlations
print(f"\n--- Correlation checks ---")

print(f"\n  vs P₊/P₋:")
print(f"    deg2 ∩ P₊ = {sorted(deg2 & P_PLUS)}  ({len(deg2 & P_PLUS)})")
print(f"    deg2 ∩ P₋ = {sorted(deg2 & P_MINUS)} ({len(deg2 & P_MINUS)})")
print(f"    deg1 ∩ P₊ = {sorted(deg1 & P_PLUS)}  ({len(deg1 & P_PLUS)})")
print(f"    deg1 ∩ P₋ = {sorted(deg1 & P_MINUS)} ({len(deg1 & P_MINUS)})")
if deg2 == P_PLUS or deg2 == P_MINUS:
    print(f"    ★ Degree-2 = {'P₊' if deg2 == P_PLUS else 'P₋'}!")
else:
    print(f"    → No exact match with P₊/P₋")

print(f"\n  vs Blocks:")
for i, bl in enumerate(BLOCKS):
    d2 = sorted(deg2 & bl)
    d1 = sorted(deg1 & bl)
    print(f"    Block {i} {sorted(bl)}: deg2={d2}, deg1={d1}")

# One from each block?
blocks_of_deg2 = set(next(i for i, bl in enumerate(BLOCKS) if t in bl) for t in deg2)
blocks_of_deg1 = set(next(i for i, bl in enumerate(BLOCKS) if t in bl) for t in deg1)
print(f"    Blocks represented in deg2: {sorted(blocks_of_deg2)}")
print(f"    Blocks represented in deg1: {sorted(blocks_of_deg1)}")
if blocks_of_deg2 == {0, 1, 2, 3}:
    print(f"    ★ Degree-2 takes exactly 1 from each block!")
    # Which one from each block?
    for i, bl in enumerate(BLOCKS):
        member = deg2 & bl
        print(f"      Block {i}: degree-2 member = {sorted(member)}")

print(f"\n  vs Yang-count:")
for t in sorted(deg2):
    print(f"    deg2: {t} yang_count={BINARY[t].count('1')}")
for t in sorted(deg1):
    print(f"    deg1: {t} yang_count={BINARY[t].count('1')}")

yang_counts_deg2 = [BINARY[t].count('1') for t in deg2]
yang_counts_deg1 = [BINARY[t].count('1') for t in deg1]
print(f"    deg2 yang counts: {sorted(yang_counts_deg2)} (mean={sum(yang_counts_deg2)/len(yang_counts_deg2):.2f})")
print(f"    deg1 yang counts: {sorted(yang_counts_deg1)} (mean={sum(yang_counts_deg1)/len(yang_counts_deg1):.2f})")

# Yang-count parity
yang_even = frozenset(t for t in TRIGRAMS if BINARY[t].count('1') % 2 == 0)
yang_odd = frozenset(t for t in TRIGRAMS if BINARY[t].count('1') % 2 == 1)
print(f"\n  vs Yang-count parity:")
print(f"    Yang-even (0,2): {sorted(yang_even)}")
print(f"    Yang-odd  (1,3): {sorted(yang_odd)}")
if deg2 == yang_even or deg2 == yang_odd:
    print(f"    ★ Degree-2 = yang-{'even' if deg2==yang_even else 'odd'}!")
else:
    print(f"    → No match")

# Check: is deg2 = P₋ (intercardinal)?
print(f"\n  Direct comparison:")
print(f"    deg2 = {sorted(deg2)}")
print(f"    P₋   = {sorted(P_MINUS)}")
print(f"    Match: {deg2 == P_MINUS}")
print(f"    deg1 = {sorted(deg1)}")
print(f"    P₊   = {sorted(P_PLUS)}")
print(f"    Match: {deg1 == P_PLUS}")


# ═══════════════════════════════════════════════════════════════
# FINAL SYNTHESIS
# ═══════════════════════════════════════════════════════════════

print("\n\n" + "=" * 70)
print("ROUND 2 SYNTHESIS")
print("=" * 70)

print("""
Key findings from the three computations:

1. COMPOSITION: ι ∘ 六合 and 六合 ∘ ι are generally NOT functions
   (six合 maps some trigrams to 2 neighbors, others to 1).
   No composition produces a clean involution.

2. BIPARTITION: The 六合 graph is bipartite but disconnected,
   so the bipartition is NOT unique. The multiple valid colorings
   mean we cannot extract a single canonical partition from 六合 alone.

3. DEGREE STRUCTURE: The degree-2 vs degree-1 split is the most
   informative structural feature of the 六合 graph.
""")

# Save results
output_path = '/home/quasar/nous/memories/iching/spaceprobe/q4/round2_results.md'
with open(output_path, 'w') as f:
    f.write("# Round 2: 六合 Deep Analysis Results\n\n")
    
    f.write("## 1. Composition with Involutions\n\n")
    f.write("The relational compositions ι ∘ 六合 and 六合 ∘ ι are generally **not functions**.\n")
    f.write("六合 maps degree-2 nodes to 2 neighbors, so composition produces multi-valued results.\n")
    f.write("No composition yields a clean involution.\n\n")
    
    f.write("## 2. Perfect Matchings within 六合\n\n")
    f.write(f"Found {len(perfect_matchings)} perfect matching(s) extractable from 六合's 6 edges:\n\n")
    for i, m in enumerate(perfect_matchings):
        f.write(f"### Matching {i+1}\n")
        for p in sorted(m, key=lambda x: sorted(x)):
            a, b = sorted(p)
            f.write(f"- {a} ↔ {b}\n")
        perm = {}
        for p in m:
            a, b = list(p)
            perm[a] = b
            perm[b] = a
        group = generate_group()
        in_group = any(all(g[t] == perm[t] for t in TRIGRAMS) for g in group)
        for name, inv in KNOWN_INVOLUTIONS.items():
            if m == inv:
                f.write(f"\n**Matches {name}**\n\n")
                break
        else:
            f.write(f"\nNew involution (not ι₁, ι₂, ι₃, or τ). In S₄ group: {'Yes' if in_group else 'No'}\n\n")
    
    if extended_matchings:
        f.write("## 3. Extended Matchings (3 from 六合 + 1 unclaimed)\n\n")
        for i, (m, added) in enumerate(extended_matchings):
            a_add, b_add = sorted(added)
            f.write(f"### Extended Matching {i+1} (added {a_add}↔{b_add})\n")
            for p in sorted(m, key=lambda x: sorted(x)):
                a, b = sorted(p)
                marker = " ← added" if p == added else ""
                f.write(f"- {a} ↔ {b}{marker}\n")
            perm = {}
            for p in m:
                a, b = list(p)
                perm[a] = b
                perm[b] = a
            in_group = any(all(g[t] == perm[t] for t in TRIGRAMS) for g in group)
            for name, inv in KNOWN_INVOLUTIONS.items():
                if m == inv:
                    f.write(f"\n**Matches {name}**\n\n")
                    break
            else:
                f.write(f"\nIn S₄ group: {'Yes' if in_group else 'No'}\n\n")
    
    f.write("## 4. Bipartition\n\n")
    f.write(f"六合 graph is bipartite with {len(components) if len(components) > 1 else 1} connected component(s).\n")
    if len(components) > 1:
        f.write(f"Disconnected → bipartition NOT unique ({2**len(components)} valid 2-colorings).\n\n")
    else:
        f.write(f"Connected → bipartition is unique.\n\n")
    
    f.write("## 5. Degree Structure\n\n")
    f.write(f"- Degree-2: {sorted(deg2)}\n")
    f.write(f"- Degree-1: {sorted(deg1)}\n\n")
    if deg2 == P_MINUS:
        f.write("**★ Degree-2 = P₋ (intercardinal/Lo Shu even)!**\n\n")
        f.write("This means the 六合 graph's degree structure independently identifies\n")
        f.write("the polarity partition P₊/P₋, without reference to Lo Shu numbers or binary encoding.\n")
    elif deg2 == P_PLUS:
        f.write("**★ Degree-2 = P₊ (cardinal/Lo Shu odd)!**\n\n")
    else:
        f.write("Degree-2 does not match P₊ or P₋.\n\n")
    
    f.write("## 6. Verdict\n\n")
    if deg2 == P_PLUS or deg2 == P_MINUS:
        f.write("**六合 is INFORMATIVE**: its degree structure independently determines\n")
        f.write("the polarity partition, making it a genuinely independent witness to P₊/P₋.\n")
        f.write("This is the strongest result of Round 1+2.\n")
    else:
        f.write("六合 is COMPATIBLE with the block structure but does not independently\n")
        f.write("determine the polarity partition from its graph-theoretic properties alone.\n")

print(f"\nResults saved to: {output_path}")
